language: java
services:
  - docker
env:
  - CHANGE_MINIKUBE_NONE_USER=true
before_script:
  - chmod +x ../test/runJavaOpenliberty.sh
script: 
  - sudo mount --make-rshared /
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x kubectl
  - sudo ln -s $(pwd)/kubectl /usr/local/bin/kubectl
  - wget https://github.com/kubernetes/minikube/releases/download/v0.28.2/minikube-linux-amd64 -q -O minikube
  - chmod +x minikube
  - sudo ln -s $(pwd)/minikube /usr/local/bin/minikube
  - sudo minikube start --vm-driver=none --bootstrapper=localkube
  - kubectl config use-context minikube
  - curl -L https://mirror.openshift.com/pub/openshift-v4/clients/odo/latest/odo-linux-amd64 -o /usr/local/bin/odo
  - chmod +x /usr/local/bin/odo
  - mkdir myapp
  - cp devfile.yml myapp/devfile.yml
  - cd myapp
  - odo create project myapp
  - odo create --starter
  - odo push
